Some hacks to /src makefile so it'll work better with vala and gob

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1,97 +1,119 @@
+NULL=
+
 REVISION=$(shell git rev-parse --short master)
 CONF_VERSION=0
 -include Makefile.config
 
 bin_PROGRAMS=stuffkeeper
 
+stuffkeeper_GOBFILES=\
+     	stuffkeeper-data-backend.gob \
+	stuffkeeper-data-boolean.gob \
+	stuffkeeper-data-date2.gob \
+	stuffkeeper-data-entry-config.gob \
+	stuffkeeper-data-entry.gob \
+	stuffkeeper-data-expander.gob \
+	stuffkeeper-data-image.gob \
+	stuffkeeper-data-item.gob \
+	stuffkeeper-data-item-search.gob \
+	stuffkeeper-data-label.gob \
+	stuffkeeper-data-link.gob \
+	stuffkeeper-data-list2.gob \
+	stuffkeeper-data-password-config.gob \
+	stuffkeeper-data-password.gob \
+	stuffkeeper-data-rating.gob \
+	stuffkeeper-data-schema.gob \
+	stuffkeeper-data-spinbutton-config.gob \
+	stuffkeeper-data-spinbutton.gob \
+	stuffkeeper-data-tag.gob \
+	stuffkeeper-data-taglist2.gob \
+	stuffkeeper-data-text.gob \
+	stuffkeeper-edit-schema.gob \
+	stuffkeeper-export-html.gob \
+	stuffkeeper-interface.gob \
+	stuffkeeper-item-view.gob \
+	stuffkeeper-item-window.gob \
+	stuffkeeper-plugin.gob \
+	stuffkeeper-plugin-manager.gob \
+	stuffkeeper-show-item.gob \
+	$(NULL)
+
+stuffkeeper_GOBSOURCES=\
+	$(stuffkeeper_GOBFILES:.gob=.c) \
+	$(stuffkeeper_GOBFILES:.gob=.h) \
+	$(stuffkeeper_GOBFILES:.gob=-private.h) \
+	$(NULL)
+
+stuffkeeper_VALAFILES=\
+	stuffkeeper-data-boolean-config.vala \
+	stuffkeeper-data-rating-config.vala \
+	$(NULL)
+
+stuffkeeper_VALASOURCES=\
+	$(stuffkeeper_VALAFILES:.vala=.c) \
+	$(stuffkeeper_VALAFILES:.vala=.h) \
+	$(NULL)
+
 ##
 # These files should be compiled, but may _not_ be
 # in the dist
 ##
 nodist_stuffkeeper_SOURCES=\
-	stuffkeeper-data-backend.c\
-	stuffkeeper-data-schema.c\
-	stuffkeeper-data-boolean.c\
-	stuffkeeper-data-boolean-config.c\
-	stuffkeeper-data-spinbutton.c\
-	stuffkeeper-data-spinbutton-config.c\
-	stuffkeeper-data-date2.c\
-	stuffkeeper-data-tag.c\
-	stuffkeeper-data-entry.c\
-	stuffkeeper-data-entry-config.c\
-	stuffkeeper-data-password.c\
-	stuffkeeper-data-password-config.c\
-	stuffkeeper-data-taglist2.c\
-	stuffkeeper-data-expander.c\
-	stuffkeeper-data-text.c\
-	stuffkeeper-data-image.c\
-	stuffkeeper-edit-schema.c\
-	stuffkeeper-data-item-search.c\
-	stuffkeeper-export-html.c\
-	stuffkeeper-data-item.c\
-	stuffkeeper-interface.c\
-	stuffkeeper-data-label.c\
-	stuffkeeper-item-view.c\
-	stuffkeeper-data-link.c\
-	stuffkeeper-item-window.c\
-	stuffkeeper-data-list2.c\
-	stuffkeeper-show-item.c\
-	stuffkeeper-data-rating.c\
-	stuffkeeper-data-rating-config.c\
-	stuffkeeper-plugin.c\
-	stuffkeeper-plugin-manager.c
+	$(stuffkeeper_GOBSOURCES) \
+	$(stuffkeeper_VALASOURCES) \
+	$(NULL)
 ##
 # Sources that should be in the distribution 
 ##
 stuffkeeper_SOURCES=\
-	misc.c\
-	main.c\
-	debug.c\
-	sexy-icon-entry.c\
-	bacon-message-connection.c
-
+	revisiont.h \
+    	bacon-message-connection.c \
+	bacon-message-connection.h \
+	debug.c \
+	debug.h \
+	main.c \
+	misc.c \
+	misc.h \
+	sexy-icon-entry.c \
+	sexy-icon-entry.h \
+	stuffkeeperglue.h \
+	$(NULL)
 
 ##
 # Generated sources
 ##
-BUILT_SOURCES= revisiont.h\
-	stuffkeeper-data-backend.c\
-	stuffkeeper-data-schema.c\
-	stuffkeeper-data-boolean.c\
-	stuffkeeper-data-boolean-config.c\
-	stuffkeeper-data-spinbutton.c\
-	stuffkeeper-data-spinbutton-config.c\
-	stuffkeeper-data-date2.c\
-	stuffkeeper-data-tag.c\
-	stuffkeeper-data-entry.c\
-	stuffkeeper-data-entry-config.c\
-	stuffkeeper-data-password.c\
-	stuffkeeper-data-password-config.c\
-	stuffkeeper-data-taglist2.c\
-	stuffkeeper-data-expander.c\
-	stuffkeeper-data-text.c\
-	stuffkeeper-data-image.c\
-	stuffkeeper-edit-schema.c\
-	stuffkeeper-data-item-search.c\
-	stuffkeeper-export-html.c\
-	stuffkeeper-data-item.c\
-	stuffkeeper-interface.c\
-	stuffkeeper-data-label.c\
-	stuffkeeper-item-view.c\
-	stuffkeeper-data-link.c\
-	stuffkeeper-item-window.c\
-	stuffkeeper-data-list2.c\
-	stuffkeeper-show-item.c\
-	stuffkeeper-data-rating.c\
-	stuffkeeper-data-rating-config.c\
-	stuffkeeper-plugin.c\
-	stuffkeeper-plugin-manager.c
+BUILT_SOURCES=\
+	revisiont.h \
+	stuffkeeper.vala.stamp \
+	$(stuffkeeper_GOBSOURCES) \
+	$(stuffkeeper_VALASOURCES) \
+	$(NULL)
 
-%.c: %.gob
+%.c %.h %.private.h: %.gob
 	@GOB2@ --no-touch-headers --always-private-header $<
 
-%.c: %.vala
-	@VALAC@ -C --vapidir=$(top_srcdir)/vala/ --pkg=gtk+-2.0 --pkg=glib-2.0 --pkg=gmodule-2.0 --pkg=stuffkeeper $<
+stuffkeeper.vala.stamp: $(stuffkeeper_VALAFILES)
+	@rm -f stuffkeeper.vala.tmp
+	@touch -f stuffkeeper.vala.tmp
+	@VALAC@ -C --vapidir=$(top_srcdir)/vala/ --pkg=gtk+-2.0 --pkg=glib-2.0 \
+		--pkg=gmodule-2.0 --pkg=stuffkeeper $^
+	@mv -f stuffkeeper.vala.tmp $@
+
+# Handle the case where a vala file was deleted but not the stamp file
+# This code avoids problems with parallel compilation by using an empty 
+# directory as a lock mechanism
+$(stuffkeeper_VALASOURCES): stuffkeeper.vala.stamp
+	@if test -f $@; then :; else \
+		trap 'rm -rf $<.lock $<' 1 2 13 15; \
+		if mkdir $<.lock 2>/dev/null; then \
+			rm -f $<; \
+			$(MAKE) $(AM_MAKEFLAGS) $<; \
+			rmdir $<.lock; \
+		else ;
+			while test -d $<.lock; do sleep 1; done; \
+			test -f $<; exit $$?; \
+		fi; \
+	fi
 
 revisiont.h:
 	@if test '$(REVISION)' != '$(CONF_VERSION)'; then\
@@ -100,10 +122,6 @@ revisiont.h:
 		echo "CONF_VERSION=$(REVISION)" > Makefile.config;\
 	fi;
 
-INCLUDES= -Wall\
-	-DPIXMAP_PATH=\""$(pkgdatadir)"\" \
-	-DGLADE_PATH=\""$(pkgdatadir)"\" \
-	-DVERSION=\"@VERSION@\"
 
 LIBS= \
 	@glib_LIBS@\
@@ -115,86 +133,63 @@ LIBS= \
 	@sqlite3_LIBS@\
 	@gthread_LIBS@\
 	@gio_LIBS@\
-	@GPGME_LIBS@
+	@GPGME_LIBS@ \
+	$(NULL)
 
 
 AM_LDFLAGS = \
-	@LDFLAGS@
+	@LDFLAGS@ \
+	$(NULL)
 
-AM_CFLAGS = @CFLAGS@\
-	@glib_CFLAGS@\
-	@gobject_CFLAGS@\
-	@gtk_CFLAGS@\
-	@gmodule_CFLAGS@\
-	@libglade_CFLAGS@\
-	@sqlite3_CFLAGS@\
-	@gthread_CFLAGS@\
-	@gio_CFLAGS@\
-	@GPGME_CFLAGS@\
-	-DPACKAGE_LIB_DIR=\""$(pkglibdir)"\"
+AM_CFLAGS = \
+	@CFLAGS@ \
+	@glib_CFLAGS@ \
+	@gobject_CFLAGS@ \
+	@gtk_CFLAGS@ \
+	@gmodule_CFLAGS@ \
+	@libglade_CFLAGS@ \
+	@sqlite3_CFLAGS@ \
+	@gthread_CFLAGS@ \
+	@gio_CFLAGS@ \
+	@GPGME_CFLAGS@ \
+	-DPACKAGE_LIB_DIR=\""$(pkglibdir)"\" \
+	-Wall\
+	-DPIXMAP_PATH=\""$(pkgdatadir)"\" \
+	-DGLADE_PATH=\""$(pkgdatadir)"\" \
+	-DVERSION=\"@VERSION@\" \
+	$(NULL)
 
 ##
 # Should be installed so plugins can be compiled
 ##
 nodist_stuffkeeperinclude_HEADERS = \
-    stuffkeeperglue.h\
+	stuffkeeperglue.h\
 	stuffkeeper-data-item.h\
 	stuffkeeper-data-schema.h\
 	stuffkeeper-data-backend.h\
 	stuffkeeper-data-tag.h\
 	stuffkeeper-plugin.h\
 	stuffkeeper-interface.h\
-	stuffkeeper-data-item-search.h
+	stuffkeeper-data-item-search.h\
+	$(NULL)
 
 stuffkeeperincludedir =$(includedir)/stuffkeeper/
 
 ##
 # Extra files that should be shipped with the distributions.
-# This include gob files and header files 
+# This include gob files and vala files 
 ##
 EXTRA_DIST=\
-		   bacon-message-connection.h\
-		   debug.h\
-		   misc.h\
-		   sexy-icon-entry.h\
-		   stuffkeeperglue.h\
-		   stuffkeeper-data-backend.gob\
-		   stuffkeeper-data-boolean.gob\
-		   stuffkeeper-data-boolean-config.vala\
-		   stuffkeeper-data-date2.gob\
-		   stuffkeeper-data-entry.gob\
-		   stuffkeeper-data-entry-config.gob\
-		   stuffkeeper-data-password.gob\
-		   stuffkeeper-data-password-config.gob\
-		   stuffkeeper-data-expander.gob\
-		   stuffkeeper-data-image.gob\
-		   stuffkeeper-data-item.gob\
-		   stuffkeeper-data-item-search.gob\
-		   stuffkeeper-data-label.gob\
-		   stuffkeeper-data-link.gob\
-		   stuffkeeper-data-list2.gob\
-		   stuffkeeper-data-rating.gob\
-		   stuffkeeper-data-rating-config.vala\
-		   stuffkeeper-data-schema.gob\
-		   stuffkeeper-data-spinbutton.gob\
-	stuffkeeper-data-spinbutton-config.gob\
-		   stuffkeeper-data-tag.gob\
-		   stuffkeeper-data-taglist2.gob\
-		   stuffkeeper-data-text.gob\
-		   stuffkeeper-edit-schema.gob\
-		   stuffkeeper-export-html.gob\
-		   stuffkeeper-interface.gob\
-		   stuffkeeper-item-view.gob\
-		   stuffkeeper-item-window.gob\
-		   stuffkeeper-plugin.gob\
-		   stuffkeeper-plugin-manager.gob\
-		   stuffkeeper-show-item.gob
+	$(stuffkeeper_GOBFILES) \
+	$(stuffkeeper_VALAFILES) \
+	Makefile.config \
+	$(NULL)
 
 ##
-# Removes all generated files, use DISTCLEANFILES for this?
+# Cleanup generated files
 ##
-clean-local:
-	-rm stuffkeeper-*.h
-	-rm stuffkeeper-*.c revision.h
-	-rm Makefile.config
-	-rm revision.h
+CLEANFILES=\
+	stuffkeeper.vala.stamp \
+	$(stuffkeeper_GOBSOURCES) \
+	$(stuffkeeper_VALASOURCES) \
+	$(NULL)
